

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(here)

```

# CV Frederik Heitmüller
Updated: `r format(Sys.Date(), "%d %b %Y")` | [Web version](https://fheitmueller.github.io/cv/) | [PDF version](https://github.com/fheitmueller/cv/raw/master/cv_Heitmuller.pdf)

I am a Research Consultant at the [International Centre for Tax and Development (ICTD)](https://www.ictd.ac/) and a PhD Candidate and Teacher at Leiden University's Institute for Tax Law and Economics in the [GLOBTAXGOV Project](https://globtaxgov.weblog.leidenuniv.nl/) (since 2018, prospectively until 2023). My research focuses on policies against corporate tax avoidance, the influence of international norms in the Global South and tax policy for development. I work in an interdisciplinary way and I aim at contributing to the state of the art in political science and tax law scholarship. My PhD thesis is supervised by [Prof. Dr. Irma Mosquera](https://www.universiteitleiden.nl/medewerkers/irma-mosquera-valderrama#tab-1) and [Prof. Dr. Madeleine Hosli](https://www.universiteitleiden.nl/medewerkers/madeleine-hosli#tab-1). 

## Contact information

[f.heitmuller@law.leidenuniv.nl](mailto:f.heitmuller@law.leidenuniv.nl) | [f.heitmuller@ictd.ac](mailto:f.heitmuller@ictd.ac) | [Twitter](https://twitter.com/HeitmuellerF) | [LinkedIn](https://www.linkedin.com/in/frederik-heitm%C3%BCller-6b041314a/) | [GitHub](https://github.com/fheitmueller) 

## Research
### Peer-reviewed journal articles

* _Special Economic Zones Facing the Challenges of International Taxation: BEPS Action 5, EU Code of Conduct, and the Future_ (with Irma Mosquera), Journal of International Economic Law, Volume 24, Issue 2, June 2021, Pages 473–490 - [Paper](https://doi.org/10.1093/jiel/jgab019) -  [Slides](http://globtaxgov.weblog.leidenuniv.nl/files/2020/10/Heitm%C3%BCller_Mosquera_SEZ_taxation.pdf) - [Data](https://github.com/fheitmueller/sez_beps)

### Reports and toolkits

* _Toolkit for the Design and Effective Implementation of Domestic and International General Anti-Avoidance Rules_ (with Juliana Cubillos and Irma Mosquera), Published by Inter-American Center of Tax Administrations (CIAT), 2022. -  [report in English](https://biblioteca.ciat.org/opac/book/5804) - [report in Spanish](https://biblioteca.ciat.org/opac/book/5803)

### Book chapters

* _Multilateral Cooperation in International Tax Law_ (with Juliana Cubillos and Irma Mosquera). In: The Future of Multilateralism: Global Cooperation and International Organizations (ed.: Madeleine O. Hosli, Taylor Garrett, Sonja Niedecken, Nicolas Verbeek). 2021. Lanham (Maryland): Rowman & Littlefield -  [Pre-Print](http://globtaxgov.weblog.leidenuniv.nl/files/2021/08/Multilateral-Cooperation-in-International-Tax-Law.pdf)

### Policy briefs
*	_Corporate Tax, Digitalization and Globalization_ (with Irma Mosquera). World Economic Forum White Paper. 2019 - [Paper](http://www3.weforum.org/docs/WEF_Corporate_Tax_Digitalization_and_Globalization.pdf)

### Working papers and Conference papers
* _Inclusive and Effective International Tax Cooperation: Views From the Global South_ (with Lucinda Cadzow, Martin Hearson, Katharina Kuhn, Okanga Okanga, and Tovony Randriamanalina), ICTD Working Paper 172, 2023 - [Paper](https://www.ictd.ac/publication/inclusive-effective-international-tax-cooperation/)
* _Tax Treaty Norms Among Lower-Income Countries and the Role of the UN Model: Past, Present and Potential_ (with Martin Hearson and Vincent Arel-Bundock), ICTD Working Paper 171, 2023  - [Paper](https://www.ictd.ac/publication/tax-treaty-norms-among-lower-income-countries/)
*	_Regulatory Capacity of Corporate Registries in the European Union. Survey Results_ (with Moran Harari and Markus Meinzer), 2019 - [Paper](https://www.taxjustice.net/wp-content/uploads/2019/02/Administrative-capacity-of-corporate-registries-Tax-Justice-Network-Feb-2019.pdf)
*	_Tax administrations' capacity tax evasion and tax avoidance_ (with Moran Harari and Markus Meinzer), presented at the “New Perspectives on Tax Administration Research” conference at CESIfo, Munich, November 2-3, 2018. - [Paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3300589)
*	_Citizenship and Residency by Investment Schemes: Potential to Avoid the Common Reporting Standard for Automatic Exchange of Information_”_ (with Andres Knobel). 2018 - [Paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3144444)

### Blogs
* _Are G7 countries doing developing countries a favour when levying global minimum taxes?_ GLOBTAXGOV Blog. 10 June 2021 - [Link](https://globtaxgov.weblog.leidenuniv.nl/2021/06/10/are-g7-countries-doing-developing-countries-a-favour-when-levying-global-minimum-taxes/)
* _Corporate income taxation and COVID-19 – time to think about a European tax?_ GLOBTAXGOV Blog. 5 June 2020 - [Link](https://globtaxgov.weblog.leidenuniv.nl/2020/06/05/corporate-income-taxation-and-covid-19-time-to-think-about-a-european-tax/)
* _Are clubs still the right place to deal with the great problems of our time? – Insights from the conference “G20 @ 10”_ GLOBTAXGOV Blog. 23 November 2018 - [Link](https://globtaxgov.weblog.leidenuniv.nl/2018/11/23/are-clubs-still-the-right-place-to-deal-with-the-great-problems-of-our-time-insights-from-the-conference-g20-10/)

## Teaching
### As (co-)instructor
* International Tax Law for MNEs, Law Faculty, Leiden University, Fall 2023
* Policy coherence to achieve the Sustainable Development Goals from a tax, trade and investment law perspective, Honour's College, Leiden University, Fall 2023 
* Comparative Tax Law, Law Faculty, Leiden University, Spring 2023 and Fall 2023
* EU and Tax Sovereignty: Discussing the Role of the EU In International Tax Law Making, at Leiden University, Faculty for Global Governance and Affairs, MSc International Relations and Diplomacy Program (MIRD), Fall 2022
* Navigating Global Tax Governance. A series of 5 workshops for tax officials in Africa, in cooperation with [African Tax Administration Forum](www.ataftax.org/). February and March 2022

### As guest lecturer
* "The taxation of global corporations", 1 May 2023, at Erasmus University College, Rotterdam

## Other academic activities
### Co-organizer 
* "Taxation, State Capacity, and Accountable Rule", workshop at the 2022 ECPR Joint Sessions (with Anna Persson)
* Research Colloquium on Global Tax Governance (with Irma Mosquera and Martin Hearson)
* Global Governance Gap Research Group at Leiden Law School (with Sarah Vandenbroucke)

### Reviewer
* Intertax
* Regulation & Governance
* Nordic Journal for Law and Society
* Journal of Tax Administration
* Journal of International Economic Law
* University of Curaçao

## Previous affiliations
* 05/2018 – 08/2018	Researcher at The Tax Justice Network / COFFERS project
* 11/2017 – 04/2018 Intern at GIZ – Deutsche Gesellschaft für Internationale Zusammenarbeit
* 09/2017 – 11/2017	Consultant at The Tax Justice Network

## Education
* 2015 – 2017 	M.A. „Empirical Political and Social Research (Franco-German)“ at University of Stuttgart and M.A. „Bordeaux International Relations Degree” at Sciences Po Bordeaux (double-degree program)
* 2016 Non-degree program at Middlebury Institute for International Studies, Monterey, California (specialization: International Trade)
* 2012 – 2015 	B.A. „Social Sciences (Franco-German)“ at University of Stuttgart and Sciences Po Bordeaux (double-degree program)

## Language skills
* English (fluent)
* French (fluent)
* Spanish (fluent)
* Dutch (fluent)
* German (mother tongue)

## Other skills
* R (statistical programming language) (advanced)





